### PR TITLE
Add support for Cygwin/git-bash on windows

### PR DESCRIPTION
**Pull request by nshtg**
On windows rust and zr produce invalid paths which are not working in `bash`:

```sh
# zsh-users/prezto
source C:\cygwin64\home\Max/.zr\plugins\zsh-users\prezto\modules/history/init.zsh
fpath+=C:\cygwin64\home\Max/.zr\plugins\zsh-users\prezto\modules/history/
PATH=C:\cygwin64\home\Max/.zr\plugins\zsh-users\prezto\modules/history:$PATH
```

I implemented a version using `cygpath` to acquire the correct paths:

```sh
# zsh-users/prezto
source /home/Max/.zr/plugins/zsh-users/prezto/modules/history/init.zsh
fpath+=/home/Max/.zr/plugins/zsh-users/prezto/modules/history/
PATH=/home/Max/.zr/plugins/zsh-users/prezto/modules/history:$PATH
```

However if `cygpath` is not available the program will crash. 

A tradeoff I would be willing to make since I don't know any decent way to use `zsh` on windows without cygwin.

### CODE REVIEW

**Comment by nshtg** [comment]
@jedahan ?

**Comment by jedahan** [comment]
ahh sorry @nshtg so I think what I need to do is use path.join instead of manually writing out the paths and rust will handle the correct slashes. I'll try it out right now.

**Comment by nshtg** [comment]
I don't thiink so. Windows uses backslashes so technically rust does the right thing. 

Cygwin/Git-Bash just use unix slashes and that's the problem.

**Comment by jedahan** [comment]
So then this pull request would fail for people not using cygwin but are on windows? I wonder if I can runtime check what environment we are in and fix it that way.

**Comment by jedahan** [comment]
related issue https://github.com/sharkdp/fd/issues/153

**Comment by jedahan** [comment]
And an alright workaround for https://github.com/sharkdp/fd/pull/176

**Comment by nshtg** [comment]
Yes basically.

But I don't think you can use zsh on windows without cygwin/git-bash anyways?!

**Comment by jedahan** [comment]
Yeah there are also some other hardcoded paths with forward slashes, can you test out this version for me to make sure it works?

**Pull request closed without merging**
